import { StyleSheet } from "react-native";
import { COLORS } from "./constants";
import { cloneElement } from "react";
import { Platform } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: COLORS.dark,
  },
  productPage: {
    flex: 1,
    padding: 20,
    backgroundColor: COLORS.dark,
  },
  modalContainer: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? 50 : 0,
    backgroundColor: COLORS.dark,
  },
  text: {
    fontSize: 20,
    fontWeight: "600",
    color: COLORS.light,
    width: "50%",
  },
  smalltext: {
    fontSize: 19,
    color: COLORS.light,
  },
  heading: {
    fontSize: 32,
    color: COLORS.primary,
    textAlign: "center",
    fontWeight: "700",
  },
  loginbox: {
    padding: 10,
    alignSelf: "center",
    margin: 20,
    flex: 1,
    width: "100%",
    backgroundColor: COLORS.primary,
    borderRadius: 15,
    gap: 10,
    justifyContent: "space-around",
  },
  inputbox: {
    backgroundColor: "white",
    height: 45,
    padding: 10,
    fontSize: 23,
    color: COLORS.dark,
    borderRadius: 7,
    width: "80%",
    alignSelf: "center",
  },
  loginbutton: {
    margin: 10,
    backgroundColor: "#000",
    padding: 10,
    textAlign: "center",
    borderRadius: 7,
    alignContent: "center",
  },
  loginButtonText: {
    color: "#fff",
    fontSize: 25,
    textAlign: "center",
  },
  bookbox: {
    borderColor: COLORS.primary,
    borderWidth: 1,
    borderStyle: "solid",
    borderRadius: 10,
    backgroundColor: "black",
    marginBottom: 10,
    padding: 10,
    borderRadius: 10,
    flex: 1,
    justifyContent: "space-between",
  },
  bookboxLeft: {},
  bookboxRight: {
    flex: 1,
    alignItems: "center",
    position: "absolute",
    justifyContent: "center",
    right: 20,
    top: 25,
    backgroundColor: COLORS.secondary,
    borderRadius: 7,
    paddingHorizontal: 5,
  },
  numCopies: {
    fontSize: 20,
    color: "#fff",
    textAlign: "center",
    fontWeight: "700",
  },
  oldPriceContainer: {
    flex: 1,
    alignItems: "center",
    position: "absolute",
    justifyContent: "center",
    right: 20,
    top: 70,
    paddingRight: "25",
    borderRadius: 7,
    padding: 10,
  },
  oldPrice: {
    fontSize: 20,
    color: "#999",
    textAlign: "center",
    fontWeight: "500",
    textDecorationLine: "line-through",
  },
  title: { margin: 10, fontSize: 30, color: COLORS.primary, fontWeight: "900" },
  author: {
    margin: 10,
    fontSize: 25,
    color: "#fff",
    fontWeight: "300",
  },
  year: { margin: 10, fontSize: 25, color: "#Fff", fontWeight: "200" },
  rentDuration: {
    margin: 10,
    fontSize: 20,
    color: COLORS.primary,
    fontWeight: "200",
    fontStyle: "italic",
  },
  booksLeft: {
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    backgroundColor: COLORS.primary,
    fontSize: 20,
    textAlign: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 7,
    margin: 10,
  },
  booksLeftText: {
    backgroundColor: COLORS.primary,
    color: "#000",
    fontSize: 20,
    textAlign: "center",
  },

  thumbnail: {
    width: 300,
    height: 300,
    borderRadius: 10,
    alignSelf: "center",
    margin: 20,
    elevation: 10,
  },
  thumbSmall: {
    width: 80,
    height: 130,
    margin: 20,
    borderRadius: 10,
    elevation: 10,
    overflow: "visible",
  },
  thumbSmallContainer: {
    borderRadius: 10,
  },
  thumbCart: {
    maxWidth: 80,
    height: 130,
    margin: 20,
    borderRadius: 10,
    elevation: 10,
    overflow: "visible",
  },
  itemContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  cameraContainer: {
    flex: 0.9,
    borderRadius: 7,
    overflow: "hidden",
    gap: 1,
    height: 500,
  },
  camera: { flex: 1 },
  promoContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
  },
  promoblock: {
    backgroundColor: COLORS.secondary,
    borderRadius: 7,
  },
  promocode: {
    color: "#fff",
    fontSize: 25,
    margin: 5,
    textAlign: "center",
    fontWeight: "900",
  },
  promotext: { fontSize: 15, margin: 5, textAlign: "center" },
  buttonContainer: { overflow: "hidden" },
  button: {
    backgroundColor: "#000",
    borderBottomEndRadius: 7,
    height: 40,
    width: 40,
    color: "#000",
    justifyContent: "center",
    alignItems: "center",
  },
  windowButton: {},
  cartItem: {
    borderWidth: 1,
    borderRadius: 7,
    paddingHorizontal: 40,
    paddingVertical: 20,
    backgroundColor: COLORS.primary,
    marginBottom: 10,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5.62,
    elevation: 7,
    overflow: "visible",
    zIndex: 9,
  },
  qtyBlock: {
    flexDirection: "row",
    backgroundColor: "#fff",
    justifyContent: "space-between",
    borderRadius: 7,
    width: 140,
    alignSelf: "flex-end",
  },
  qtyButton: {
    backgroundColor: "#000",
    borderRadius: 7,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    textAlignVertical: "center",
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.2,
    shadowRadius: 5.62,
    elevation: 7,
  },
  qtyText: {
    color: "#fff",
    fontSize: 30,
    alignSelf: "center",
  },
  removeButton: {
    position: "absolute",
    right: 10,
    top: 10,
  },
  priceContainer: {},
  price: {
    backgroundColor: COLORS.primary,
    borderRadius: 7,
    padding: 5,
    alignSelf: "flex-start",
    justifyContent: "center",
    alignItems: "center",
  },
  priceText: {
    textAlign: "left",
    color: "#000",
    fontSize: 25,
    fontWeight: "700",
  },
  oldPriceDetail: {
    fontSize: 20,
    color: "#aaa",
    textDecorationLine: "line-through",
  },
  off: {
    backgroundColor: COLORS.secondary,
    color: "#fff",
  },
});
