import { StyleSheet } from "react-native";
import { COLORS } from "./constants";
import { cloneElement } from "react";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.dark,
    padding: 12,
  },
  text: {
    fontSize: 20,
    fontWeight: "600",
    color: COLORS.light,
    width: "50%",
  },
  smalltext: {
    fontSize: 19,
    color: COLORS.light,
  },
  heading: {
    fontSize: 32,
    color: COLORS.primary,
    textAlign: "center",
    fontWeight: "700",
  },
  loginbox: {
    alignSelf: "center",
    padding: 50,
    margin: 50,
    flex: 1,
    width: "80%",
    backgroundColor: COLORS.primary,
    borderRadius: 15,
    gap: 10,
    justifyContent: "space-around",
  },
  inputbox: {
    backgroundColor: "white",
    height: 45,
    padding: 10,
    fontSize: 23,
    color: COLORS.dark,
    borderRadius: 7,
  },
  loginbutton: {
    margin: 10,
    backgroundColor: "#fff",
    padding: 10,
    textAlign: "center",
    borderRadius: 7,
    alignContent: "center",
  },
  loginButtonText: {
    fontSize: 25,
    textAlign: "center",
  },
  bookbox: {
    borderColor: COLORS.primary,
    borderWidth: 1,
    borderStyle: "solid",
    borderRadius: 10,
    backgroundColor: "black",
    marginBottom: 10,
    padding: 10,
    borderRadius: 10,
    flex: 1,
    justifyContent: "space-between",
  },
  bookboxLeft: {},
  bookboxRight: {
    flex: 1,
    alignItems: "center",
    position: "absolute",
    justifyContent: "center",
    right: 20,
    top: 25,
    paddingRight: "25",
    backgroundColor: COLORS.secondary,
    borderRadius: 7,
    padding: 10,
  },
  numCopies: {
    fontSize: 20,
    color: "#fff",
    textAlign: "center",
    fontWeight: 900,
  },
  title: { margin: 10, fontSize: 30, color: COLORS.primary, fontWeight: "900" },
  author: {
    margin: 10,
    fontSize: 30,
    color: "#fff",
    fontWeight: "300",
  },
  year: { margin: 10, fontSize: 25, color: "#Fff", fontWeight: "200" },
  rentDuration: {
    margin: 10,
    fontSize: 20,
    color: COLORS.primary,
    fontWeight: "200",
    fontStyle: "italic",
  },
  booksLeft: {
    backgroundColor: COLORS.primary,
    color: "#fff",
    fontSize: 20,
    textAlign: "center",
    padding: 10,
    borderRadius: 7,
    margin: 20,
  },
  booksLeftText: {
    backgroundColor: COLORS.primary,
    color: "#fff",
    fontSize: 20,
    textAlign: "center",
  },

  thumbnail: {
    width: 300,
    height: 400,
    borderRadius: 10,
    alignSelf: "center",
    margin: 20,
    shadowColor: "#fff",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.5,
    shadowRadius: 6.27,
    elevation: 10,
  },
  thumbSmall: {
    width: 80,
    height: 130,
    margin: 20,
    borderRadius: 10,
    shadowColor: "#fff",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.5,
    shadowRadius: 6.27,
    elevation: 10,
    overflow: "visible",
  },
  thumbSmallContainer: {
    borderRadius: 10,
  },
  itemContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  cameraContainer: {
    flex: 1,
    borderRadius: 7,
    overflow: "hidden",
    height: 500,
  },
  camera: { flex: 1 },
  buttonContainer: {},
  button: {},
});
