name: Build and Release APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.6.2

      - name: Install dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Log in to Expo
        run: expo login --non-interactive --access-token ${{ secrets.EXPO_TOKEN }}

      - name: Build standalone APK
        run: expo build:android -t apk --local

      - name: Download APK
        uses: wei/pull@v1
        with:
          repo: expo/expo
          path: './artifacts'
          filter: '*.apk'

      - name: Upload APK to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: './artifacts/app.apk'
          asset_name: 'app.apk'
          asset_content_type: 'application/vnd.android.package-archive'
