name: Build and Release APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.6.2

      - name: Install dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Log in to Expo
        run: expo login --non-interactive --access-token ${{ secrets.EXPO_TOKEN }}

      - name: Build standalone APK
        run: expo build:android -t apk --local
        id: build

      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: releases/app.apk
